---
  version: '2'
  services:
    my-dev-box:
      image: openjdk:8
      volumes:
        - /Users/ali/confluent-5.1.0:/confluent
      command: tail -F anything
      environment:
        ZK: zookeeper:2181
        KAFKA: kafka-1:9092,kafka-2:9092,kafka-3:9092
  
    postgres:
      image: debezium/postgres:9.6
      hostname: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: inventory
  
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      hostname: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
  
    kafka-1:
      image: confluentinc/cp-enterprise-kafka:latest
      hostname: kafka-1
      ports:
        - "19092:19092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_CLIENT_PORT: 19092
        KAFKA_BROKER_ID: 1
        KAFKA_BROKER_RACK: rack-a
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:19092
  
    kafka-2:
      image: confluentinc/cp-enterprise-kafka:latest
      hostname: kafka-2
      ports:
        - "29092:29092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_CLIENT_PORT: 29092
        KAFKA_BROKER_ID: 2
        KAFKA_BROKER_RACK: rack-a
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:29092
  
    kafka-3:
      image: confluentinc/cp-enterprise-kafka:latest
      hostname: kafka-3
      ports:
        - "39092:39092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_CLIENT_PORT: 39092
        KAFKA_BROKER_ID: 3
        KAFKA_BROKER_RACK: rack-a
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:39092
  
    connect:
      image: debezium/connect
      hostname: debezium
      ports:
       - 8083:8083
       - 5005:5005
      depends_on:
        - kafka-1
        - kafka-2
        - kafka-3
      links:
        - kafka-1
        - kafka-2
        - kafka-3
        - postgres
      environment:
       - BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
       - GROUP_ID=1
       - CONFIG_STORAGE_TOPIC=my_connect_configs
       - OFFSET_STORAGE_TOPIC=my_connect_offsets
       - STATUS_STORAGE_TOPIC=my_source_connect_statuses
  
  volumes:
    confluent:
